name: shpp
description: SHPP.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  go_router: ^13.2.3
  auto_size_text: ^3.0.0
  before_after: ^3.0.0+1
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  visibility_detector: ^0.4.0+2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  country_flags: ^2.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  photo_view: ^0.14.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  generate: true
  uses-material-design: true
