name: shpp
description: SHPP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.16.0
  go_router: ^11.1.2
  auto_size_text: ^3.0.0
  before_after: ^3.0.0+1
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  visibility_detector: ^0.4.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  uses-material-design: true
